### ISSUE TITLE
[BUG] 2.0.3 update causes 'Tuple' object has no attribute 'value'

### ISSUE THREAD

**Issue by sdebruyn** [hadialqattan/pycln#161]
After the update from 2.0.2 to 2.0.3 I get 100+ errors mentioning `'Tuple' object has no attribute 'value'`
The code with the error doesn't have any tuples, however its imports do have an `from typing import Tuple`

Python 3.9, ubuntu 20.04

**Comment by Kaelten** [comment]
I'm seeing this with both `Tuple` and `Name` in multiple files in my project.  However, I'm not even seeing those keys in the files

**Comment by Kaelten** [comment]
I've worked up a simple reproduction case:

It appears that the fixes to allow generic types to work better now have an issue if you don't use a string in the generic type definition.

This generates the error ` 'Name' object has no attribute 'value'`:

```python
def reproduction(value: list[dict]) -> None:
    pass
```

This works fine:
```python
def reproduction(value: list['dict']) -> None:
    pass
```

If you do the below you get `'BinOp' object has no attribute 'value'`

```python
def reproduction(value: list[int | str]) -> None:
    pass
```

I've not figured out exactly what can trigger the `Tuple` version of this error, but it all appears to be a lack of type checking when parsing the subtype of the generics?

**Comment by hadialqattan** [comment]
Hi, I'm so sorry for that...this issue is under investigation right now. Thank you both @sdebruyn for reporting the issue and @Kaelten for giving further details.

**Comment by hadialqattan** [comment]
After investigating, this seems to be related to some `ast` module changes in Python3.9+...

**Comment by hadialqattan** [comment]
I'll fix it as soon as possible and release v2.0.4...

**Comment by Kaelten** [comment]
Thanks for the prompt engagement on both this and my last report! :)

**Comment by hadialqattan** [comment]
> I've not figured out exactly what can trigger the `Tuple` version of this error, but it all appears to be a lack of type checking when parsing the subtype of the generics?

https://github.com/hadialqattan/pycln/blob/d1ac94fd9fa743d9570e6268a3f94c6bee1d8ece/pycln/utils/scan.py#L381-L396

It's line 394.

**Comment by hadialqattan** [comment]
actually using the else statement in line388 and 394 is a really bad idea 😓

**Comment by Kaelten** [comment]
> actually using the else statement in line388 and 394 is a really bad idea 😓

I almost always wonder wtf past me was thinking when I'm bug fixing <_<

**Comment by hadialqattan** [comment]
> > actually using the else statement in line388 and 394 is a really bad idea 😓
> 
> I almost always wonder wtf past me was thinking when I'm bug fixing <_<

That always happens, actually, this time I've well tested the edge cases but I've missed the normal/main one 😂.

**Comment by hadialqattan** [comment]
@Kaelten if you don't mind, could you double-check my fix? PR #162 

I mean running it against some possible edge cases (if any).

**Comment by hadialqattan** [comment]
> @Kaelten if you don't mind, could you double-check my fix? PR #162
> 
> I mean running it against some possible edge cases (if any).

for now, I'll merge the PR and create a new release so this issue affects fewer projects. in case you have any updates please let me know.

\+ Thanks a lot for your support.

**Comment by Kaelten** [comment]
@hadialqattan I've tested 2.0.4 against my project and both #161 and #154 are looking good.  Thanks again!
