### ISSUE TITLE
[BUG] fails removing unused import when in a tuple

### ISSUE THREAD

**Issue by gboutry** [hadialqattan/pycln#172]
**Describe the bug** pycln fails to remove unused imports if they are in a tuple

**To Reproduce** Steps to reproduce the behavior:

1. Take this code snippet:

   ```python
    from typing import Any, Dict, List
    
    def nothing(a: List[str]) -> Any:
        return a
   ```

2. Run this Pycln command:
   ```bash
   $ pycln test.py
   ```
3. Error traceback or unexpected output (if present):

   ```bash
    test.py:1:0 'from typing import Dict' was removed! 🔮
    test.py:1:34 libcst.ParserSyntaxError: Internal error: __init__() got an unexpected keyword argument '__slots__': 'from typing import Any, Dict, List' ⛔

    Oh no, there was an error! 💔 ☹️
    1 import was removed, 1 file left unchanged, 1 file has failed to be cleaned.
   ```

4. Unexpected fixed code (if present):

   >

   ```python

   ```

**Expected behavior**:

1.  Description: A clear and concise description of what you expected to happen.
  PyCln should remove the `Dict` from the import without failing
3.  Expected output (if present):

    ```bash

    ```

4.  Expected fixed code (if present):

    >

    ```python
    from typing import Any, List
    
    def nothing(a: List[str]) -> Any:
        return a
    ```

**Environment (please complete the following informations):**

- Python Version: Python 3.6.15
- Pycln Version: 2.1.1
- OS Type: Linux Fedora 36

**Additional context**
The following versions did not work either: 1.3.5, 2.0.1, 2.0.4
This works with pycln=1.2.0

**Comment by hadialqattan** [comment]
@gboutry Thanks for reporting the issue. Clearly, the issue was with `LibCST >=0.4.1` and `Python 3.6`.

**Comment by gboutry** [comment]
@hadialqattan It works as expected in python 3.6, thank you very much!
